version: '3.7'

services:
  addboxs_www:
    container_name: addboxs_www
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/:cached
    environment:
      APP_ENV: local
      NODE_ENV: local
      HTTPS_METHOD: noredirect # support both http and https
    environment:
      APP_ENV: local
    networks:
      network-inewgent:

networks:
  network-inewgent:
    external: true